/**
 * Mock provider — zero external dependencies, zero network calls.
 * This is what makes the platform runnable end-to-end (section 30, Demo
 * Data) before anyone adds a real ANTHROPIC_API_KEY/OPENAI_API_KEY. It
 * produces structurally correct, deterministic output so every downstream
 * step (SEO optimization, quality scoring, publishing) has something real
 * to operate on.
 *
 * It is intentionally simple template logic, not a language model — swap
 * AI_DEFAULT_PROVIDER to "anthropic" once a key is configured to get real
 * generated content instead.
 */

import type { AiProvider, AiCompletionRequest, AiCompletionResult } from "./provider";

function estimateTokens(text: string): number {
  // Rough heuristic: ~4 chars/token, good enough for demo-mode bookkeeping.
  return Math.max(1, Math.round(text.length / 4));
}

function buildMockResponse(req: AiCompletionRequest): string {
  switch (req.taskType) {
    case "TOPIC_DISCOVERY":
      return JSON.stringify(
        {
          keywords: [
            { phrase: "best budget option for beginners", intent: "commercial", estimatedVolume: 2400 },
            { phrase: "how does it actually work", intent: "informational", estimatedVolume: 5200 },
            { phrase: "top 10 comparison guide", intent: "comparison", estimatedVolume: 1800 },
          ],
        },
        null,
        2
      );
    case "KEYWORD_CLUSTERING":
      return JSON.stringify(
        { pillar: "Main Topic Guide", supporting: ["Sub-angle 1", "Sub-angle 2", "Sub-angle 3"] },
        null,
        2
      );
    case "CONTENT_BRIEF":
      return JSON.stringify(
        {
          h1: "A clear, benefit-led H1 for the target keyword",
          outline: [
            { h2: "What it is and who it's for" },
            { h2: "Key factors to consider", h3: ["Factor A", "Factor B", "Factor C"] },
            { h2: "Our top picks / recommendation" },
            { h2: "Frequently asked questions" },
          ],
          faqs: [
            { question: "Placeholder question relevant to the keyword?", answer: "Placeholder answer — replace with real research." },
          ],
        },
        null,
        2
      );
    case "ARTICLE_DRAFT":
      return [
        "# [Draft heading — mock content, replace by connecting a real provider]",
        "",
        "This is placeholder body content generated by the offline mock provider so the full",
        "publishing pipeline (SEO optimization, quality scoring, internal linking, scheduling)",
        "can be exercised end-to-end without an API key.",
        "",
        "## Key considerations",
        "- Point one drawn from the content brief.",
        "- Point two drawn from the content brief.",
        "",
        "## Frequently asked questions",
        "**Placeholder question?** Placeholder answer.",
      ].join("\n");
    case "SEO_OPTIMIZATION":
      return JSON.stringify(
        {
          metaTitle: "Concise, keyword-led title under 60 characters",
          metaDescription: "Actionable meta description under 155 characters that earns the click.",
          slug: "target-keyword-slug",
        },
        null,
        2
      );
    case "FACT_CHECK":
      return JSON.stringify({ unsupportedClaims: [], confidence: 92 }, null, 2);
    case "IMAGE_BRIEF":
      return "A clean, well-lit editorial photo illustrating the article's main subject, no text overlay.";
    case "SOCIAL_REPURPOSE":
      return JSON.stringify(
        {
          x: "Hook line + link. Under 280 characters.",
          linkedin: "A slightly longer, professional framing with a question to drive comments.",
          pinterest: "Benefit-led description with the primary keyword near the front.",
        },
        null,
        2
      );
    case "NEWSLETTER":
      return "Subject: New this week\n\nA short digest summarizing the latest published article and one recommended product.";
    case "NICHE_ANALYSIS":
      return JSON.stringify({ note: "Use src/lib/ai/niche-analyzer.ts for real scoring — this mock text is illustrative only." }, null, 2);
    case "DECAY_ANALYSIS":
      return JSON.stringify({ note: "Use src/lib/ai/content-decay.ts for real scoring — this mock text is illustrative only." }, null, 2);
    case "QUALITY_SCORE":
      return JSON.stringify({ note: "Use src/lib/ai/quality-score.ts for real scoring — this mock text is illustrative only." }, null, 2);
    default:
      return "Mock provider: no template defined for this task type.";
  }
}

export class MockProvider implements AiProvider {
  name = "mock" as const;

  async complete(req: AiCompletionRequest): Promise<AiCompletionResult> {
    const text = buildMockResponse(req);
    return {
      text,
      provider: "mock",
      model: "mock",
      promptTokens: estimateTokens(req.prompt),
      completionTokens: estimateTokens(text),
      cached: false,
    };
  }
}
